FROM golang:1.20.5-alpine as builder

WORKDIR /usr/app
COPY . .
RUN go mod download

ENV CGO_ENABLED=0
RUN go build -a -installsuffix cgo -o ./build/app . 

FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /usr/app

COPY --from=builder /usr/app/build/app .

CMD ["./app"]